name: Hoyolab Genshin Auto Login

on:
   schedule:
      - cron: "0 18 * * *" # scheduled at 06:00 (UTC+8) everyday
   workflow_dispatch:

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: ">=12.14.1"
         - name: Install dependencies
           run: npm ci

         - name: Genshin Impact login
           run: node genshin.js
           env:
              HOYOLAB_COOKIE: ${{ secrets.HOYOLAB_COOKIE }}
